### ISSUE TITLE
Use renovate for checking dependencies update

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#121]
## Purpose
Feature request

## Description
依存関係のアップデートやそのチェックに renovate を使いたい

## TODO
- [x] app-template-vite
- [x] app-template-nestjs
- [x] app-data-browser-next
- [x] app-user-manager
- [x] app-launcher-next
- [x] app-scene-viewer

**Comment by WatanabeToshimitsu** [comment]
app-scene-viewer はリポジトリ構造が特殊なので保留
