### ISSUE TITLE
Replace eslint-config-standard to eslint-config-airbnb

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#122]
## Purpose
Feature request

## Description
eslint-config-standard は開発スピードがゆっくりっぽく、eslint を長いこと v8 にアップデートできていないので eslint-config-airbnb にして eslint のアップデートに追従したい

## TODO
- [ ] app-template-vite
- [ ] app-template-nestjs
- [ ] app-scene-viewer
- [ ] app-data-browser
- [ ] app-user-manager
- [ ] app-scene-viewer
