### ISSUE TITLE
[data-browser] Show easy understood error

### ISSUE THREAD

**Issue by yusukefs** [dataware-tools/dataware-tools#22]
## Purpose

feature request

## Description

今は返ってきたオブジェクトをそのまま表示してるだけで理解が難しい

## TODOs
- [x] data-browser
- [x] user-manager
- [x] api-meta-store
- [x] api-file-provider
- [x] api-permission-manager
- [x] api-job-store

**Comment by WatanabeToshimitsu** [comment]
バックエンドの対応も行う

**Comment by WatanabeToshimitsu** [comment]
All task completed
