### ISSUE TITLE
ログイン後のリダイレクト先を origin/callback にする

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#71]
## Purpose
- feature request

## Description
ログイン後のリダイレクト先を origin/callback にする

## ToDo
- [x] app-common
- [x] app-data-browser-next
- [x] app-user-manager
- [x] app-template-nextjs

**Comment by WatanabeToshimitsu** [comment]
https://github.com/dataware-tools/app-common/blob/master/src/components/Header.tsx#L84 を `window.location.origin/callback` にする
https://github.com/dataware-tools/app-common/blob/master/src/components/Header.tsx#L86 を window.location.href にする

**Comment by WatanabeToshimitsu** [comment]
Completed!
