### ISSUE TITLE
Unify UX of pull-down menu in UserList and RoleEditorModal

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#77]
## Purpose
Feature request

## Description
ユーザごとの Role を選択するためのプルダウンメニューとデータベースごとの permission を選択するためのプルダウンメニューでUXが異なっているので、どちらかに統一したい

具体的な違いは以下の通り

### Role 選択メニュー
<img width="560" alt="スクリーンショット 2021-06-08 12 25 01" src="https://user-images.githubusercontent.com/24401842/121118325-9e164600-c854-11eb-9c9f-cc5589262e0a.png">
項目選択後にメニュー外の場所をクリックすると `キャンセル` になる

### Permission 選択メニュー
<img width="473" alt="スクリーンショット 2021-06-08 12 24 45" src="https://user-images.githubusercontent.com/24401842/121118306-9191ed80-c854-11eb-854a-09e10c6f4a63.png">
項目選択後にメニュー外の場所をクリックすると `確定` になる

## See also
- https://github.com/dataware-tools/app-user-manager/issues/74

## TODO
- [ ] `api-permission-manager` にユーザのRoleを一括で更新するメソッドを追加する
- [ ] user-manager の `Users` 画面のマルチセレクトのUXを `Roles` 画面のものに統一する
- [ ] ページネーションへの対応

**Comment by d-hayashi** [comment]
TODO:
- [ ] `api-permission-manager` にユーザのRoleを一括で更新するメソッドを追加する
- [ ] user-manager の `Users` 画面のマルチセレクトのUXを `Roles` 画面のものに統一する
- [ ] ページネーションへの対応

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi @yuri-sakai 
この issue なんですが，問題は「同じ見た目の UI が同じ操作に対して違う応答を返す」とこにあると考えてます
なので，ひとまず Role 選択メニューの側の Save ボタンをなくして，Premission 選択メニューと同様の操作感にする，というとこで留めておくのはどうでしょうか？
それを触ってみた上で，まとめて保存する機能なり Undo 機能なりの追加を検討した方が良いんじゃないかと！

**Comment by yuri-sakai** [comment]
@WatanabeToshimitsu 
返事遅くなってすみません。良いと思います！
