### ISSUE TITLE
Add test process to CI into front end application repository

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#78]
## Purpose
- feature request

## Description
- github action か lint-staged にテストプロセスを入れたい

## TODO
- [x] app-template-nextjs
- [x] app-user-manager
- [x] app-data-browser
- [x] app-common

**Comment by d-hayashi** [comment]
TODO:
- [ ] app-template-nextjs
- [ ] app-user-manager
- [ ] app-data-browser
- [ ] app-common

**Comment by WatanabeToshimitsu** [comment]
app-common はライブラリなので， github ホストマシン上で直接テストを実行する
matrix を使って広い環境でテストできるように出来ると良い
https://docs.github.com/ja/actions/guides/building-and-testing-nodejs

フロントリポジトリは，デプロイ用のイメージを流用する
マルチステージビルドでステージを分岐？すると良さげ

**Comment by WatanabeToshimitsu** [comment]
Completed!
